//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XAdo.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyPerson
    {
        public FamilyPerson()
        {
            this.FamilyPerson1 = new HashSet<FamilyPerson>();
            this.FamilyPerson11 = new HashSet<FamilyPerson>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> FatherId { get; set; }
        public Nullable<int> MotherId { get; set; }
    
        public virtual ICollection<FamilyPerson> FamilyPerson1 { get; set; }
        public virtual FamilyPerson FamilyPerson2 { get; set; }
        public virtual ICollection<FamilyPerson> FamilyPerson11 { get; set; }
        public virtual FamilyPerson FamilyPerson3 { get; set; }
    }
}
