
//------------------------------------------------------------------------------
// <auto-generated timestamp="2016-11-30T20:07:03.1133421Z">
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using XAdo.Quobs.Core.DbSchema.Attributes;

namespace DbSchema.Users
{
   public abstract partial class DbBaseTable : IDbTable {}
   
   [Table("Role", Schema="dbo")]
   [ReferencedBy(new []{typeof(DbUserRole)})]
   public partial class DbRole : DbBaseTable
   {
      [Key, DbAutoIncrement, DbUnique, Required]
      public virtual Int32? Id {get; set;}
      [Required, MaxLength(50)]
      public virtual String Name {get; set;}
   }
   [Table("sysdiagrams", Schema="dbo")]
   public partial class Dbsysdiagrams : DbBaseTable
   {
      [Required, MaxLength(128)]
      public virtual String name {get; set;}
      [Required]
      public virtual Int32? principal_id {get; set;}
      [Key, DbAutoIncrement, DbUnique, Required]
      public virtual Int32? diagram_id {get; set;}
      public virtual Int32? version {get; set;}
      public virtual Byte[] definition {get; set;}
   }
   [Table("User", Schema="dbo")]
   [ReferencedBy(new []{typeof(DbUserRole)})]
   public partial class DbUser : DbBaseTable
   {
      [Key, DbAutoIncrement, DbUnique, Required]
      public virtual Int32? Id {get; set;}
      [Required, MaxLength(256)]
      public virtual String UserName {get; set;}
      [MaxLength(256)]
      public virtual String Email {get; set;}
      [MaxLength(256)]
      public virtual String Password {get; set;}
   }
   [Table("UserRole", Schema="dbo")]
   public partial class DbUserRole : DbBaseTable
   {
      [Key, DbAutoIncrement, DbUnique, Required]
      public virtual Int32? Id {get; set;}
      [Required]
      [References( Type=typeof(DbUser), MemberName="Id", ColumnName="Id", FKeyName="FK_UserRole_User")]
      public virtual Int32? UserId {get; set;}
      [Required]
      [References( Type=typeof(DbRole), MemberName="Id", ColumnName="Id", FKeyName="FK_UserRole_Role")]
      public virtual Int32? RoleId {get; set;}
   }
   
   public static partial class JoinExtension
   {
      [JoinMethod(RelationshipName="FK_UserRole_Role")]
      public static DbRole Role(this DbUserRole self, JoinType join){return null;}
      [JoinMethod(RelationshipName="FK_UserRole_Role")]
      public static DbRole Role(this DbUserRole self){return null;}
      [JoinMethod(RelationshipName="FK_UserRole_User")]
      public static DbUser User(this DbUserRole self, JoinType join){return null;}
      [JoinMethod(RelationshipName="FK_UserRole_User")]
      public static DbUser User(this DbUserRole self){return null;}
      // joins for child relations
      [JoinMethod(RelationshipName="FK_UserRole_Role", Reversed=true)]
      public static DbUserRole UserRole_N(this DbRole self, JoinType join){return null;}
      [JoinMethod(RelationshipName="FK_UserRole_Role", Reversed = true)]
      public static DbUserRole UserRole_N(this DbRole self){return null;}
      [JoinMethod(RelationshipName="FK_UserRole_User", Reversed=true)]
      public static DbUserRole UserRole_N(this DbUser self, JoinType join){return null;}
      [JoinMethod(RelationshipName="FK_UserRole_User", Reversed = true)]
      public static DbUserRole UserRole_N(this DbUser self){return null;}
   }
}


