
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Microsoft.SqlServer.Types;
using XAdo.Quobs.Attributes;

namespace XAdo.Quobs.Generator
{
   [Table(TableName = "Person.Address")]
   public partial class DbAddress
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? AddressID{get; set;}
      public virtual String AddressLine1{get; set;}
      public virtual String AddressLine2{get; set;}
      public virtual String City{get; set;}
      public virtual Int32? StateProvinceID{get; set;}
      public virtual String PostalCode{get; set;}
      public virtual SqlGeography SpatialLocation{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Person.AddressType")]
   public partial class DbAddressType
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? AddressTypeID{get; set;}
      public virtual String Name{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "dbo.AWBuildVersion")]
   public partial class DbAWBuildVersion
   {
      [Column(IsPKey = true)]
      public virtual Byte? SystemInformationID{get; set;}
      [Column(ColumnName = "Database Version")]
      public virtual String Database_Version{get; set;}
      public virtual DateTime? VersionDate{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.BillOfMaterials")]
   public partial class DbBillOfMaterials
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? BillOfMaterialsID{get; set;}
      public virtual Int32? ProductAssemblyID{get; set;}
      public virtual Int32? ComponentID{get; set;}
      public virtual DateTime? StartDate{get; set;}
      public virtual DateTime? EndDate{get; set;}
      public virtual String UnitMeasureCode{get; set;}
      public virtual Int16? BOMLevel{get; set;}
      public virtual Decimal? PerAssemblyQty{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Person.BusinessEntity")]
   public partial class DbBusinessEntity
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Person.BusinessEntityAddress")]
   public partial class DbBusinessEntityAddress
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      [Column(IsPKey = true)]
      public virtual Int32? AddressID{get; set;}
      [Column(IsPKey = true)]
      public virtual Int32? AddressTypeID{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Person.BusinessEntityContact")]
   public partial class DbBusinessEntityContact
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      [Column(IsPKey = true)]
      public virtual Int32? PersonID{get; set;}
      [Column(IsPKey = true)]
      public virtual Int32? ContactTypeID{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Person.ContactType")]
   public partial class DbContactType
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? ContactTypeID{get; set;}
      public virtual String Name{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Person.CountryRegion")]
   public partial class DbCountryRegion
   {
      [Column(IsPKey = true)]
      public virtual String CountryRegionCode{get; set;}
      public virtual String Name{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.CountryRegionCurrency")]
   public partial class DbCountryRegionCurrency
   {
      [Column(IsPKey = true)]
      public virtual String CountryRegionCode{get; set;}
      [Column(IsPKey = true)]
      public virtual String CurrencyCode{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.CreditCard")]
   public partial class DbCreditCard
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? CreditCardID{get; set;}
      public virtual String CardType{get; set;}
      public virtual String CardNumber{get; set;}
      public virtual Byte? ExpMonth{get; set;}
      public virtual Int16? ExpYear{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.Culture")]
   public partial class DbCulture
   {
      [Column(IsPKey = true)]
      public virtual String CultureID{get; set;}
      public virtual String Name{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.Currency")]
   public partial class DbCurrency
   {
      [Column(IsPKey = true)]
      public virtual String CurrencyCode{get; set;}
      public virtual String Name{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.CurrencyRate")]
   public partial class DbCurrencyRate
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? CurrencyRateID{get; set;}
      public virtual DateTime? CurrencyRateDate{get; set;}
      public virtual String FromCurrencyCode{get; set;}
      public virtual String ToCurrencyCode{get; set;}
      public virtual Decimal? AverageRate{get; set;}
      public virtual Decimal? EndOfDayRate{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.Customer")]
   public partial class DbCustomer
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? CustomerID{get; set;}
      public virtual Int32? PersonID{get; set;}
      public virtual Int32? StoreID{get; set;}
      public virtual Int32? TerritoryID{get; set;}
      public virtual String AccountNumber{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "dbo.DatabaseLog")]
   public partial class DbDatabaseLog
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? DatabaseLogID{get; set;}
      public virtual DateTime? PostTime{get; set;}
      public virtual String DatabaseUser{get; set;}
      public virtual String Event{get; set;}
      public virtual String Schema{get; set;}
      public virtual String Object{get; set;}
      public virtual String TSQL{get; set;}
      public virtual String XmlEvent{get; set;}
   }
   
   [Table(TableName = "HumanResources.Department")]
   public partial class DbDepartment
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int16? DepartmentID{get; set;}
      public virtual String Name{get; set;}
      public virtual String GroupName{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.Document")]
   public partial class DbDocument
   {
      [Column(IsPKey = true)]
      public virtual SqlHierarchyId? DocumentNode{get; set;}
      public virtual Int16? DocumentLevel{get; set;}
      public virtual String Title{get; set;}
      public virtual Int32? Owner{get; set;}
      public virtual Boolean? FolderFlag{get; set;}
      public virtual String FileName{get; set;}
      public virtual String FileExtension{get; set;}
      public virtual String Revision{get; set;}
      public virtual Int32? ChangeNumber{get; set;}
      public virtual Byte? Status{get; set;}
      public virtual String DocumentSummary{get; set;}
      public virtual Byte[] Document{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Person.EmailAddress")]
   public partial class DbEmailAddress
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? EmailAddressID{get; set;}
      public virtual String EmailAddress{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "HumanResources.Employee")]
   public partial class DbEmployee
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual String NationalIDNumber{get; set;}
      public virtual String LoginID{get; set;}
      public virtual SqlHierarchyId? OrganizationNode{get; set;}
      public virtual Int16? OrganizationLevel{get; set;}
      public virtual String JobTitle{get; set;}
      public virtual DateTime? BirthDate{get; set;}
      public virtual String MaritalStatus{get; set;}
      public virtual String Gender{get; set;}
      public virtual DateTime? HireDate{get; set;}
      public virtual Boolean? SalariedFlag{get; set;}
      public virtual Int16? VacationHours{get; set;}
      public virtual Int16? SickLeaveHours{get; set;}
      public virtual Boolean? CurrentFlag{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "HumanResources.EmployeeDepartmentHistory")]
   public partial class DbEmployeeDepartmentHistory
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      [Column(IsPKey = true)]
      public virtual Int16? DepartmentID{get; set;}
      [Column(IsPKey = true)]
      public virtual Byte? ShiftID{get; set;}
      [Column(IsPKey = true)]
      public virtual DateTime? StartDate{get; set;}
      public virtual DateTime? EndDate{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "HumanResources.EmployeePayHistory")]
   public partial class DbEmployeePayHistory
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      [Column(IsPKey = true)]
      public virtual DateTime? RateChangeDate{get; set;}
      public virtual Decimal? Rate{get; set;}
      public virtual Byte? PayFrequency{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "dbo.ErrorLog")]
   public partial class DbErrorLog
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? ErrorLogID{get; set;}
      public virtual DateTime? ErrorTime{get; set;}
      public virtual String UserName{get; set;}
      public virtual Int32? ErrorNumber{get; set;}
      public virtual Int32? ErrorSeverity{get; set;}
      public virtual Int32? ErrorState{get; set;}
      public virtual String ErrorProcedure{get; set;}
      public virtual Int32? ErrorLine{get; set;}
      public virtual String ErrorMessage{get; set;}
   }
   
   [Table(TableName = "Production.Illustration")]
   public partial class DbIllustration
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? IllustrationID{get; set;}
      public virtual String Diagram{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "HumanResources.JobCandidate")]
   public partial class DbJobCandidate
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? JobCandidateID{get; set;}
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual String Resume{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.Location")]
   public partial class DbLocation
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int16? LocationID{get; set;}
      public virtual String Name{get; set;}
      public virtual Decimal? CostRate{get; set;}
      public virtual Decimal? Availability{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Person.Password")]
   public partial class DbPassword
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual String PasswordHash{get; set;}
      public virtual String PasswordSalt{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Person.Person")]
   public partial class DbPerson
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual String PersonType{get; set;}
      public virtual Boolean? NameStyle{get; set;}
      public virtual String Title{get; set;}
      public virtual String FirstName{get; set;}
      public virtual String MiddleName{get; set;}
      public virtual String LastName{get; set;}
      public virtual String Suffix{get; set;}
      public virtual Int32? EmailPromotion{get; set;}
      public virtual String AdditionalContactInfo{get; set;}
      public virtual String Demographics{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.PersonCreditCard")]
   public partial class DbPersonCreditCard
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      [Column(IsPKey = true)]
      public virtual Int32? CreditCardID{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Person.PersonPhone")]
   public partial class DbPersonPhone
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      [Column(IsPKey = true)]
      public virtual String PhoneNumber{get; set;}
      [Column(IsPKey = true)]
      public virtual Int32? PhoneNumberTypeID{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Person.PhoneNumberType")]
   public partial class DbPhoneNumberType
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? PhoneNumberTypeID{get; set;}
      public virtual String Name{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.Product")]
   public partial class DbProduct
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? ProductID{get; set;}
      public virtual String Name{get; set;}
      public virtual String ProductNumber{get; set;}
      public virtual Boolean? MakeFlag{get; set;}
      public virtual Boolean? FinishedGoodsFlag{get; set;}
      public virtual String Color{get; set;}
      public virtual Int16? SafetyStockLevel{get; set;}
      public virtual Int16? ReorderPoint{get; set;}
      public virtual Decimal? StandardCost{get; set;}
      public virtual Decimal? ListPrice{get; set;}
      public virtual String Size{get; set;}
      public virtual String SizeUnitMeasureCode{get; set;}
      public virtual String WeightUnitMeasureCode{get; set;}
      public virtual Decimal? Weight{get; set;}
      public virtual Int32? DaysToManufacture{get; set;}
      public virtual String ProductLine{get; set;}
      public virtual String Class{get; set;}
      public virtual String Style{get; set;}
      public virtual Int32? ProductSubcategoryID{get; set;}
      public virtual Int32? ProductModelID{get; set;}
      public virtual DateTime? SellStartDate{get; set;}
      public virtual DateTime? SellEndDate{get; set;}
      public virtual DateTime? DiscontinuedDate{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.ProductCategory")]
   public partial class DbProductCategory
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? ProductCategoryID{get; set;}
      public virtual String Name{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.ProductCostHistory")]
   public partial class DbProductCostHistory
   {
      [Column(IsPKey = true)]
      public virtual Int32? ProductID{get; set;}
      [Column(IsPKey = true)]
      public virtual DateTime? StartDate{get; set;}
      public virtual DateTime? EndDate{get; set;}
      public virtual Decimal? StandardCost{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.ProductDescription")]
   public partial class DbProductDescription
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? ProductDescriptionID{get; set;}
      public virtual String Description{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.ProductDocument")]
   public partial class DbProductDocument
   {
      [Column(IsPKey = true)]
      public virtual Int32? ProductID{get; set;}
      [Column(IsPKey = true)]
      public virtual SqlHierarchyId? DocumentNode{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.ProductInventory")]
   public partial class DbProductInventory
   {
      [Column(IsPKey = true)]
      public virtual Int32? ProductID{get; set;}
      [Column(IsPKey = true)]
      public virtual Int16? LocationID{get; set;}
      public virtual String Shelf{get; set;}
      public virtual Byte? Bin{get; set;}
      public virtual Int16? Quantity{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.ProductListPriceHistory")]
   public partial class DbProductListPriceHistory
   {
      [Column(IsPKey = true)]
      public virtual Int32? ProductID{get; set;}
      [Column(IsPKey = true)]
      public virtual DateTime? StartDate{get; set;}
      public virtual DateTime? EndDate{get; set;}
      public virtual Decimal? ListPrice{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.ProductModel")]
   public partial class DbProductModel
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? ProductModelID{get; set;}
      public virtual String Name{get; set;}
      public virtual String CatalogDescription{get; set;}
      public virtual String Instructions{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.ProductModelIllustration")]
   public partial class DbProductModelIllustration
   {
      [Column(IsPKey = true)]
      public virtual Int32? ProductModelID{get; set;}
      [Column(IsPKey = true)]
      public virtual Int32? IllustrationID{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.ProductModelProductDescriptionCulture")]
   public partial class DbProductModelProductDescriptionCulture
   {
      [Column(IsPKey = true)]
      public virtual Int32? ProductModelID{get; set;}
      [Column(IsPKey = true)]
      public virtual Int32? ProductDescriptionID{get; set;}
      [Column(IsPKey = true)]
      public virtual String CultureID{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.ProductPhoto")]
   public partial class DbProductPhoto
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? ProductPhotoID{get; set;}
      public virtual Byte[] ThumbNailPhoto{get; set;}
      public virtual String ThumbnailPhotoFileName{get; set;}
      public virtual Byte[] LargePhoto{get; set;}
      public virtual String LargePhotoFileName{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.ProductProductPhoto")]
   public partial class DbProductProductPhoto
   {
      [Column(IsPKey = true)]
      public virtual Int32? ProductID{get; set;}
      [Column(IsPKey = true)]
      public virtual Int32? ProductPhotoID{get; set;}
      public virtual Boolean? Primary{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.ProductReview")]
   public partial class DbProductReview
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? ProductReviewID{get; set;}
      public virtual Int32? ProductID{get; set;}
      public virtual String ReviewerName{get; set;}
      public virtual DateTime? ReviewDate{get; set;}
      public virtual String EmailAddress{get; set;}
      public virtual Int32? Rating{get; set;}
      public virtual String Comments{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.ProductSubcategory")]
   public partial class DbProductSubcategory
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? ProductSubcategoryID{get; set;}
      public virtual Int32? ProductCategoryID{get; set;}
      public virtual String Name{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Purchasing.ProductVendor")]
   public partial class DbProductVendor
   {
      [Column(IsPKey = true)]
      public virtual Int32? ProductID{get; set;}
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual Int32? AverageLeadTime{get; set;}
      public virtual Decimal? StandardPrice{get; set;}
      public virtual Decimal? LastReceiptCost{get; set;}
      public virtual DateTime? LastReceiptDate{get; set;}
      public virtual Int32? MinOrderQty{get; set;}
      public virtual Int32? MaxOrderQty{get; set;}
      public virtual Int32? OnOrderQty{get; set;}
      public virtual String UnitMeasureCode{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Purchasing.PurchaseOrderDetail")]
   public partial class DbPurchaseOrderDetail
   {
      [Column(IsPKey = true)]
      public virtual Int32? PurchaseOrderID{get; set;}
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? PurchaseOrderDetailID{get; set;}
      public virtual DateTime? DueDate{get; set;}
      public virtual Int16? OrderQty{get; set;}
      public virtual Int32? ProductID{get; set;}
      public virtual Decimal? UnitPrice{get; set;}
      public virtual Decimal? LineTotal{get; set;}
      public virtual Decimal? ReceivedQty{get; set;}
      public virtual Decimal? RejectedQty{get; set;}
      public virtual Decimal? StockedQty{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Purchasing.PurchaseOrderHeader")]
   public partial class DbPurchaseOrderHeader
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? PurchaseOrderID{get; set;}
      public virtual Byte? RevisionNumber{get; set;}
      public virtual Byte? Status{get; set;}
      public virtual Int32? EmployeeID{get; set;}
      public virtual Int32? VendorID{get; set;}
      public virtual Int32? ShipMethodID{get; set;}
      public virtual DateTime? OrderDate{get; set;}
      public virtual DateTime? ShipDate{get; set;}
      public virtual Decimal? SubTotal{get; set;}
      public virtual Decimal? TaxAmt{get; set;}
      public virtual Decimal? Freight{get; set;}
      public virtual Decimal? TotalDue{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.SalesOrderDetail")]
   public partial class DbSalesOrderDetail
   {
      [Column(IsPKey = true)]
      public virtual Int32? SalesOrderID{get; set;}
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? SalesOrderDetailID{get; set;}
      public virtual String CarrierTrackingNumber{get; set;}
      public virtual Int16? OrderQty{get; set;}
      public virtual Int32? ProductID{get; set;}
      public virtual Int32? SpecialOfferID{get; set;}
      public virtual Decimal? UnitPrice{get; set;}
      public virtual Decimal? UnitPriceDiscount{get; set;}
      public virtual Decimal? LineTotal{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.SalesOrderHeader")]
   public partial class DbSalesOrderHeader
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? SalesOrderID{get; set;}
      public virtual Byte? RevisionNumber{get; set;}
      public virtual DateTime? OrderDate{get; set;}
      public virtual DateTime? DueDate{get; set;}
      public virtual DateTime? ShipDate{get; set;}
      public virtual Byte? Status{get; set;}
      public virtual Boolean? OnlineOrderFlag{get; set;}
      public virtual String SalesOrderNumber{get; set;}
      public virtual String PurchaseOrderNumber{get; set;}
      public virtual String AccountNumber{get; set;}
      public virtual Int32? CustomerID{get; set;}
      public virtual Int32? SalesPersonID{get; set;}
      public virtual Int32? TerritoryID{get; set;}
      public virtual Int32? BillToAddressID{get; set;}
      public virtual Int32? ShipToAddressID{get; set;}
      public virtual Int32? ShipMethodID{get; set;}
      public virtual Int32? CreditCardID{get; set;}
      public virtual String CreditCardApprovalCode{get; set;}
      public virtual Int32? CurrencyRateID{get; set;}
      public virtual Decimal? SubTotal{get; set;}
      public virtual Decimal? TaxAmt{get; set;}
      public virtual Decimal? Freight{get; set;}
      public virtual Decimal? TotalDue{get; set;}
      public virtual String Comment{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.SalesOrderHeaderSalesReason")]
   public partial class DbSalesOrderHeaderSalesReason
   {
      [Column(IsPKey = true)]
      public virtual Int32? SalesOrderID{get; set;}
      [Column(IsPKey = true)]
      public virtual Int32? SalesReasonID{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.SalesPerson")]
   public partial class DbSalesPerson
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual Int32? TerritoryID{get; set;}
      public virtual Decimal? SalesQuota{get; set;}
      public virtual Decimal? Bonus{get; set;}
      public virtual Decimal? CommissionPct{get; set;}
      public virtual Decimal? SalesYTD{get; set;}
      public virtual Decimal? SalesLastYear{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.SalesPersonQuotaHistory")]
   public partial class DbSalesPersonQuotaHistory
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      [Column(IsPKey = true)]
      public virtual DateTime? QuotaDate{get; set;}
      public virtual Decimal? SalesQuota{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.SalesReason")]
   public partial class DbSalesReason
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? SalesReasonID{get; set;}
      public virtual String Name{get; set;}
      public virtual String ReasonType{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.SalesTaxRate")]
   public partial class DbSalesTaxRate
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? SalesTaxRateID{get; set;}
      public virtual Int32? StateProvinceID{get; set;}
      public virtual Byte? TaxType{get; set;}
      public virtual Decimal? TaxRate{get; set;}
      public virtual String Name{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.SalesTerritory")]
   public partial class DbSalesTerritory
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? TerritoryID{get; set;}
      public virtual String Name{get; set;}
      public virtual String CountryRegionCode{get; set;}
      public virtual String Group{get; set;}
      public virtual Decimal? SalesYTD{get; set;}
      public virtual Decimal? SalesLastYear{get; set;}
      public virtual Decimal? CostYTD{get; set;}
      public virtual Decimal? CostLastYear{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.SalesTerritoryHistory")]
   public partial class DbSalesTerritoryHistory
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      [Column(IsPKey = true)]
      public virtual Int32? TerritoryID{get; set;}
      [Column(IsPKey = true)]
      public virtual DateTime? StartDate{get; set;}
      public virtual DateTime? EndDate{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.ScrapReason")]
   public partial class DbScrapReason
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int16? ScrapReasonID{get; set;}
      public virtual String Name{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "HumanResources.Shift")]
   public partial class DbShift
   {
      [Column(IsPKey = true)]
      public virtual Byte? ShiftID{get; set;}
      public virtual String Name{get; set;}
      public virtual TimeSpan? StartTime{get; set;}
      public virtual TimeSpan? EndTime{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Purchasing.ShipMethod")]
   public partial class DbShipMethod
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? ShipMethodID{get; set;}
      public virtual String Name{get; set;}
      public virtual Decimal? ShipBase{get; set;}
      public virtual Decimal? ShipRate{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.ShoppingCartItem")]
   public partial class DbShoppingCartItem
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? ShoppingCartItemID{get; set;}
      public virtual String ShoppingCartID{get; set;}
      public virtual Int32? Quantity{get; set;}
      public virtual Int32? ProductID{get; set;}
      public virtual DateTime? DateCreated{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.SpecialOffer")]
   public partial class DbSpecialOffer
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? SpecialOfferID{get; set;}
      public virtual String Description{get; set;}
      public virtual Decimal? DiscountPct{get; set;}
      public virtual String Type{get; set;}
      public virtual String Category{get; set;}
      public virtual DateTime? StartDate{get; set;}
      public virtual DateTime? EndDate{get; set;}
      public virtual Int32? MinQty{get; set;}
      public virtual Int32? MaxQty{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.SpecialOfferProduct")]
   public partial class DbSpecialOfferProduct
   {
      [Column(IsPKey = true)]
      public virtual Int32? SpecialOfferID{get; set;}
      [Column(IsPKey = true)]
      public virtual Int32? ProductID{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Person.StateProvince")]
   public partial class DbStateProvince
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? StateProvinceID{get; set;}
      public virtual String StateProvinceCode{get; set;}
      public virtual String CountryRegionCode{get; set;}
      public virtual Boolean? IsOnlyStateProvinceFlag{get; set;}
      public virtual String Name{get; set;}
      public virtual Int32? TerritoryID{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.Store")]
   public partial class DbStore
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual String Name{get; set;}
      public virtual Int32? SalesPersonID{get; set;}
      public virtual String Demographics{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "dbo.sysdiagrams")]
   public partial class Dbsysdiagrams
   {
      public virtual String name{get; set;}
      public virtual Int32? principal_id{get; set;}
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? diagram_id{get; set;}
      public virtual Int32? version{get; set;}
      public virtual Byte[] definition{get; set;}
   }
   
   [Table(TableName = "dbo.Table_1")]
   public partial class DbTable_1
   {
      [Column(IsPKey = true)]
      public virtual Int32? Id{get; set;}
      public virtual String Name{get; set;}
   }
   
   [Table(TableName = "Production.TransactionHistory")]
   public partial class DbTransactionHistory
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? TransactionID{get; set;}
      public virtual Int32? ProductID{get; set;}
      public virtual Int32? ReferenceOrderID{get; set;}
      public virtual Int32? ReferenceOrderLineID{get; set;}
      public virtual DateTime? TransactionDate{get; set;}
      public virtual String TransactionType{get; set;}
      public virtual Int32? Quantity{get; set;}
      public virtual Decimal? ActualCost{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.TransactionHistoryArchive")]
   public partial class DbTransactionHistoryArchive
   {
      [Column(IsPKey = true)]
      public virtual Int32? TransactionID{get; set;}
      public virtual Int32? ProductID{get; set;}
      public virtual Int32? ReferenceOrderID{get; set;}
      public virtual Int32? ReferenceOrderLineID{get; set;}
      public virtual DateTime? TransactionDate{get; set;}
      public virtual String TransactionType{get; set;}
      public virtual Int32? Quantity{get; set;}
      public virtual Decimal? ActualCost{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.UnitMeasure")]
   public partial class DbUnitMeasure
   {
      [Column(IsPKey = true)]
      public virtual String UnitMeasureCode{get; set;}
      public virtual String Name{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Person.vAdditionalContactInfo", Crud="R")]
   public partial class DbvAdditionalContactInfo
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual String FirstName{get; set;}
      public virtual String MiddleName{get; set;}
      public virtual String LastName{get; set;}
      public virtual String TelephoneNumber{get; set;}
      public virtual String TelephoneSpecialInstructions{get; set;}
      public virtual String Street{get; set;}
      public virtual String City{get; set;}
      public virtual String StateProvince{get; set;}
      public virtual String PostalCode{get; set;}
      public virtual String CountryRegion{get; set;}
      public virtual String HomeAddressSpecialInstructions{get; set;}
      public virtual String EMailAddress{get; set;}
      public virtual String EMailSpecialInstructions{get; set;}
      public virtual String EMailTelephoneNumber{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "HumanResources.vEmployee", Crud="R")]
   public partial class DbvEmployee
   {
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual String Title{get; set;}
      public virtual String FirstName{get; set;}
      public virtual String MiddleName{get; set;}
      public virtual String LastName{get; set;}
      public virtual String Suffix{get; set;}
      public virtual String JobTitle{get; set;}
      public virtual String PhoneNumber{get; set;}
      public virtual String PhoneNumberType{get; set;}
      public virtual String EmailAddress{get; set;}
      public virtual Int32? EmailPromotion{get; set;}
      public virtual String AddressLine1{get; set;}
      public virtual String AddressLine2{get; set;}
      public virtual String City{get; set;}
      public virtual String StateProvinceName{get; set;}
      public virtual String PostalCode{get; set;}
      public virtual String CountryRegionName{get; set;}
      public virtual String AdditionalContactInfo{get; set;}
   }
   
   [Table(TableName = "HumanResources.vEmployeeDepartment", Crud="R")]
   public partial class DbvEmployeeDepartment
   {
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual String Title{get; set;}
      public virtual String FirstName{get; set;}
      public virtual String MiddleName{get; set;}
      public virtual String LastName{get; set;}
      public virtual String Suffix{get; set;}
      public virtual String JobTitle{get; set;}
      public virtual String Department{get; set;}
      public virtual String GroupName{get; set;}
      public virtual DateTime? StartDate{get; set;}
   }
   
   [Table(TableName = "HumanResources.vEmployeeDepartmentHistory", Crud="R")]
   public partial class DbvEmployeeDepartmentHistory
   {
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual String Title{get; set;}
      public virtual String FirstName{get; set;}
      public virtual String MiddleName{get; set;}
      public virtual String LastName{get; set;}
      public virtual String Suffix{get; set;}
      public virtual String Shift{get; set;}
      public virtual String Department{get; set;}
      public virtual String GroupName{get; set;}
      public virtual DateTime? StartDate{get; set;}
      public virtual DateTime? EndDate{get; set;}
   }
   
   [Table(TableName = "Purchasing.Vendor")]
   public partial class DbVendor
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual String AccountNumber{get; set;}
      public virtual String Name{get; set;}
      public virtual Byte? CreditRating{get; set;}
      public virtual Boolean? PreferredVendorStatus{get; set;}
      public virtual Boolean? ActiveFlag{get; set;}
      public virtual String PurchasingWebServiceURL{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.vIndividualCustomer", Crud="R")]
   public partial class DbvIndividualCustomer
   {
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual String Title{get; set;}
      public virtual String FirstName{get; set;}
      public virtual String MiddleName{get; set;}
      public virtual String LastName{get; set;}
      public virtual String Suffix{get; set;}
      public virtual String PhoneNumber{get; set;}
      public virtual String PhoneNumberType{get; set;}
      public virtual String EmailAddress{get; set;}
      public virtual Int32? EmailPromotion{get; set;}
      public virtual String AddressType{get; set;}
      public virtual String AddressLine1{get; set;}
      public virtual String AddressLine2{get; set;}
      public virtual String City{get; set;}
      public virtual String StateProvinceName{get; set;}
      public virtual String PostalCode{get; set;}
      public virtual String CountryRegionName{get; set;}
      public virtual String Demographics{get; set;}
   }
   
   [Table(TableName = "HumanResources.vJobCandidate", Crud="R")]
   public partial class DbvJobCandidate
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? JobCandidateID{get; set;}
      public virtual Int32? BusinessEntityID{get; set;}
      [Column(ColumnName = "Name\\.Prefix")]
      public virtual String Name_Prefix{get; set;}
      [Column(ColumnName = "Name\\.First")]
      public virtual String Name_First{get; set;}
      [Column(ColumnName = "Name\\.Middle")]
      public virtual String Name_Middle{get; set;}
      [Column(ColumnName = "Name\\.Last")]
      public virtual String Name_Last{get; set;}
      [Column(ColumnName = "Name\\.Suffix")]
      public virtual String Name_Suffix{get; set;}
      public virtual String Skills{get; set;}
      [Column(ColumnName = "Addr\\.Type")]
      public virtual String Addr_Type{get; set;}
      [Column(ColumnName = "Addr\\.Loc\\.CountryRegion")]
      public virtual String Addr_Loc_CountryRegion{get; set;}
      [Column(ColumnName = "Addr\\.Loc\\.State")]
      public virtual String Addr_Loc_State{get; set;}
      [Column(ColumnName = "Addr\\.Loc\\.City")]
      public virtual String Addr_Loc_City{get; set;}
      [Column(ColumnName = "Addr\\.PostalCode")]
      public virtual String Addr_PostalCode{get; set;}
      public virtual String EMail{get; set;}
      public virtual String WebSite{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "HumanResources.vJobCandidateEducation", Crud="R")]
   public partial class DbvJobCandidateEducation
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? JobCandidateID{get; set;}
      [Column(ColumnName = "Edu\\.Level")]
      public virtual String Edu_Level{get; set;}
      [Column(ColumnName = "Edu\\.StartDate")]
      public virtual DateTime? Edu_StartDate{get; set;}
      [Column(ColumnName = "Edu\\.EndDate")]
      public virtual DateTime? Edu_EndDate{get; set;}
      [Column(ColumnName = "Edu\\.Degree")]
      public virtual String Edu_Degree{get; set;}
      [Column(ColumnName = "Edu\\.Major")]
      public virtual String Edu_Major{get; set;}
      [Column(ColumnName = "Edu\\.Minor")]
      public virtual String Edu_Minor{get; set;}
      [Column(ColumnName = "Edu\\.GPA")]
      public virtual String Edu_GPA{get; set;}
      [Column(ColumnName = "Edu\\.GPAScale")]
      public virtual String Edu_GPAScale{get; set;}
      [Column(ColumnName = "Edu\\.School")]
      public virtual String Edu_School{get; set;}
      [Column(ColumnName = "Edu\\.Loc\\.CountryRegion")]
      public virtual String Edu_Loc_CountryRegion{get; set;}
      [Column(ColumnName = "Edu\\.Loc\\.State")]
      public virtual String Edu_Loc_State{get; set;}
      [Column(ColumnName = "Edu\\.Loc\\.City")]
      public virtual String Edu_Loc_City{get; set;}
   }
   
   [Table(TableName = "HumanResources.vJobCandidateEmployment", Crud="R")]
   public partial class DbvJobCandidateEmployment
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? JobCandidateID{get; set;}
      [Column(ColumnName = "Emp\\.StartDate")]
      public virtual DateTime? Emp_StartDate{get; set;}
      [Column(ColumnName = "Emp\\.EndDate")]
      public virtual DateTime? Emp_EndDate{get; set;}
      [Column(ColumnName = "Emp\\.OrgName")]
      public virtual String Emp_OrgName{get; set;}
      [Column(ColumnName = "Emp\\.JobTitle")]
      public virtual String Emp_JobTitle{get; set;}
      [Column(ColumnName = "Emp\\.Responsibility")]
      public virtual String Emp_Responsibility{get; set;}
      [Column(ColumnName = "Emp\\.FunctionCategory")]
      public virtual String Emp_FunctionCategory{get; set;}
      [Column(ColumnName = "Emp\\.IndustryCategory")]
      public virtual String Emp_IndustryCategory{get; set;}
      [Column(ColumnName = "Emp\\.Loc\\.CountryRegion")]
      public virtual String Emp_Loc_CountryRegion{get; set;}
      [Column(ColumnName = "Emp\\.Loc\\.State")]
      public virtual String Emp_Loc_State{get; set;}
      [Column(ColumnName = "Emp\\.Loc\\.City")]
      public virtual String Emp_Loc_City{get; set;}
   }
   
   [Table(TableName = "Sales.vPersonDemographics", Crud="R")]
   public partial class DbvPersonDemographics
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual Decimal? TotalPurchaseYTD{get; set;}
      public virtual DateTime? DateFirstPurchase{get; set;}
      public virtual DateTime? BirthDate{get; set;}
      public virtual String MaritalStatus{get; set;}
      public virtual String YearlyIncome{get; set;}
      public virtual String Gender{get; set;}
      public virtual Int32? TotalChildren{get; set;}
      public virtual Int32? NumberChildrenAtHome{get; set;}
      public virtual String Education{get; set;}
      public virtual String Occupation{get; set;}
      public virtual Boolean? HomeOwnerFlag{get; set;}
      public virtual Int32? NumberCarsOwned{get; set;}
   }
   
   [Table(TableName = "Production.vProductAndDescription", Crud="R")]
   public partial class DbvProductAndDescription
   {
      public virtual Int32? ProductID{get; set;}
      public virtual String Name{get; set;}
      public virtual String ProductModel{get; set;}
      public virtual String CultureID{get; set;}
      public virtual String Description{get; set;}
   }
   
   [Table(TableName = "Production.vProductModelCatalogDescription", Crud="R")]
   public partial class DbvProductModelCatalogDescription
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? ProductModelID{get; set;}
      public virtual String Name{get; set;}
      public virtual String Summary{get; set;}
      public virtual String Manufacturer{get; set;}
      public virtual String Copyright{get; set;}
      public virtual String ProductURL{get; set;}
      public virtual String WarrantyPeriod{get; set;}
      public virtual String WarrantyDescription{get; set;}
      public virtual String NoOfYears{get; set;}
      public virtual String MaintenanceDescription{get; set;}
      public virtual String Wheel{get; set;}
      public virtual String Saddle{get; set;}
      public virtual String Pedal{get; set;}
      public virtual String BikeFrame{get; set;}
      public virtual String Crankset{get; set;}
      public virtual String PictureAngle{get; set;}
      public virtual String PictureSize{get; set;}
      public virtual String ProductPhotoID{get; set;}
      public virtual String Material{get; set;}
      public virtual String Color{get; set;}
      public virtual String ProductLine{get; set;}
      public virtual String Style{get; set;}
      public virtual String RiderExperience{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.vProductModelInstructions", Crud="R")]
   public partial class DbvProductModelInstructions
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? ProductModelID{get; set;}
      public virtual String Name{get; set;}
      public virtual String Instructions{get; set;}
      public virtual Int32? LocationID{get; set;}
      public virtual Decimal? SetupHours{get; set;}
      public virtual Decimal? MachineHours{get; set;}
      public virtual Decimal? LaborHours{get; set;}
      public virtual Int32? LotSize{get; set;}
      public virtual String Step{get; set;}
      public virtual Guid? rowguid{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Sales.vSalesPerson", Crud="R")]
   public partial class DbvSalesPerson
   {
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual String Title{get; set;}
      public virtual String FirstName{get; set;}
      public virtual String MiddleName{get; set;}
      public virtual String LastName{get; set;}
      public virtual String Suffix{get; set;}
      public virtual String JobTitle{get; set;}
      public virtual String PhoneNumber{get; set;}
      public virtual String PhoneNumberType{get; set;}
      public virtual String EmailAddress{get; set;}
      public virtual Int32? EmailPromotion{get; set;}
      public virtual String AddressLine1{get; set;}
      public virtual String AddressLine2{get; set;}
      public virtual String City{get; set;}
      public virtual String StateProvinceName{get; set;}
      public virtual String PostalCode{get; set;}
      public virtual String CountryRegionName{get; set;}
      public virtual String TerritoryName{get; set;}
      public virtual String TerritoryGroup{get; set;}
      public virtual Decimal? SalesQuota{get; set;}
      public virtual Decimal? SalesYTD{get; set;}
      public virtual Decimal? SalesLastYear{get; set;}
   }
   
   [Table(TableName = "Sales.vSalesPersonSalesByFiscalYears", Crud="R")]
   public partial class DbvSalesPersonSalesByFiscalYears
   {
      public virtual Int32? SalesPersonID{get; set;}
      public virtual String FullName{get; set;}
      public virtual String JobTitle{get; set;}
      public virtual String SalesTerritory{get; set;}
      [Column(ColumnName = "2002")]
      public virtual Decimal? _2002{get; set;}
      [Column(ColumnName = "2003")]
      public virtual Decimal? _2003{get; set;}
      [Column(ColumnName = "2004")]
      public virtual Decimal? _2004{get; set;}
   }
   
   [Table(TableName = "Person.vStateProvinceCountryRegion", Crud="R")]
   public partial class DbvStateProvinceCountryRegion
   {
      [Column(IsPKey = true)]
      public virtual Int32? StateProvinceID{get; set;}
      public virtual String StateProvinceCode{get; set;}
      public virtual Boolean? IsOnlyStateProvinceFlag{get; set;}
      public virtual String StateProvinceName{get; set;}
      public virtual Int32? TerritoryID{get; set;}
      [Column(IsPKey = true)]
      public virtual String CountryRegionCode{get; set;}
      public virtual String CountryRegionName{get; set;}
   }
   
   [Table(TableName = "Sales.vStoreWithAddresses", Crud="R")]
   public partial class DbvStoreWithAddresses
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual String Name{get; set;}
      public virtual String AddressType{get; set;}
      public virtual String AddressLine1{get; set;}
      public virtual String AddressLine2{get; set;}
      public virtual String City{get; set;}
      public virtual String StateProvinceName{get; set;}
      public virtual String PostalCode{get; set;}
      public virtual String CountryRegionName{get; set;}
   }
   
   [Table(TableName = "Sales.vStoreWithContacts", Crud="R")]
   public partial class DbvStoreWithContacts
   {
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual String Name{get; set;}
      public virtual String ContactType{get; set;}
      public virtual String Title{get; set;}
      public virtual String FirstName{get; set;}
      public virtual String MiddleName{get; set;}
      public virtual String LastName{get; set;}
      public virtual String Suffix{get; set;}
      public virtual String PhoneNumber{get; set;}
      public virtual String PhoneNumberType{get; set;}
      public virtual String EmailAddress{get; set;}
      public virtual Int32? EmailPromotion{get; set;}
   }
   
   [Table(TableName = "Sales.vStoreWithDemographics", Crud="R")]
   public partial class DbvStoreWithDemographics
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual String Name{get; set;}
      public virtual Decimal? AnnualSales{get; set;}
      public virtual Decimal? AnnualRevenue{get; set;}
      public virtual String BankName{get; set;}
      public virtual String BusinessType{get; set;}
      public virtual Int32? YearOpened{get; set;}
      public virtual String Specialty{get; set;}
      public virtual Int32? SquareFeet{get; set;}
      public virtual String Brands{get; set;}
      public virtual String Internet{get; set;}
      public virtual Int32? NumberEmployees{get; set;}
   }
   
   [Table(TableName = "Purchasing.vVendorWithAddresses", Crud="R")]
   public partial class DbvVendorWithAddresses
   {
      [Column(IsPKey = true)]
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual String Name{get; set;}
      public virtual String AddressType{get; set;}
      public virtual String AddressLine1{get; set;}
      public virtual String AddressLine2{get; set;}
      public virtual String City{get; set;}
      public virtual String StateProvinceName{get; set;}
      public virtual String PostalCode{get; set;}
      public virtual String CountryRegionName{get; set;}
   }
   
   [Table(TableName = "Purchasing.vVendorWithContacts", Crud="R")]
   public partial class DbvVendorWithContacts
   {
      public virtual Int32? BusinessEntityID{get; set;}
      public virtual String Name{get; set;}
      public virtual String ContactType{get; set;}
      public virtual String Title{get; set;}
      public virtual String FirstName{get; set;}
      public virtual String MiddleName{get; set;}
      public virtual String LastName{get; set;}
      public virtual String Suffix{get; set;}
      public virtual String PhoneNumber{get; set;}
      public virtual String PhoneNumberType{get; set;}
      public virtual String EmailAddress{get; set;}
      public virtual Int32? EmailPromotion{get; set;}
   }
   
   [Table(TableName = "Production.WorkOrder")]
   public partial class DbWorkOrder
   {
      [Column(IsPKey = true, IsOutputOnInsert = true)]
      public virtual Int32? WorkOrderID{get; set;}
      public virtual Int32? ProductID{get; set;}
      public virtual Int32? OrderQty{get; set;}
      public virtual Int32? StockedQty{get; set;}
      public virtual Int16? ScrappedQty{get; set;}
      public virtual DateTime? StartDate{get; set;}
      public virtual DateTime? EndDate{get; set;}
      public virtual DateTime? DueDate{get; set;}
      public virtual Int16? ScrapReasonID{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
   [Table(TableName = "Production.WorkOrderRouting")]
   public partial class DbWorkOrderRouting
   {
      [Column(IsPKey = true)]
      public virtual Int32? WorkOrderID{get; set;}
      [Column(IsPKey = true)]
      public virtual Int32? ProductID{get; set;}
      [Column(IsPKey = true)]
      public virtual Int16? OperationSequence{get; set;}
      public virtual Int16? LocationID{get; set;}
      public virtual DateTime? ScheduledStartDate{get; set;}
      public virtual DateTime? ScheduledEndDate{get; set;}
      public virtual DateTime? ActualStartDate{get; set;}
      public virtual DateTime? ActualEndDate{get; set;}
      public virtual Decimal? ActualResourceHrs{get; set;}
      public virtual Decimal? PlannedCost{get; set;}
      public virtual Decimal? ActualCost{get; set;}
      public virtual DateTime? ModifiedDate{get; set;}
   }
   
}

